(function () {
  const api = window.QualityDigitalTwinApi;
  const sessionUser = JSON.parse(localStorage.getItem('gc_user') || localStorage.getItem('grv2_user') || 'null');
  const authToken = localStorage.getItem('gc_token') || localStorage.getItem('grv2_token');
  if (!sessionUser || !authToken) { window.location.href = '../../login.html'; return; }
  const canManage = window.hasQualityPermission?.(sessionUser, 'quality.equipment.manage');
  const $ = (id) => document.getElementById(id);
  const els = { list: $('equipment-list'), feedback: $('equipment-feedback'), formCard: $('equipment-form-card'), form: $('equipment-form'), formTitle: $('equipment-form-title'), id: $('equipment-id'), zoneId: $('equipment-zone-id'), code: $('equipment-code'), name: $('equipment-name'), type: $('equipment-form-type'), manufacturer: $('equipment-manufacturer'), model: $('equipment-model'), serial: $('equipment-serial'), supplier: $('equipment-supplier'), purchaseDate: $('equipment-purchase-date'), warrantyDate: $('equipment-warranty-date'), status: $('equipment-form-status'), criticality: $('equipment-criticality'), foodContact: $('equipment-food-contact'), temperature: $('equipment-temperature'), cleaning: $('equipment-cleaning'), maintenance: $('equipment-maintenance'), calibration: $('equipment-calibration'), description: $('equipment-description'), search: $('equipment-search'), filterStatus: $('equipment-status'), filterType: $('equipment-type'), zoneFilter: $('equipment-zone-filter'), includeArchived: $('equipment-archived'), addBtn: $('equipment-add-btn'), cancelBtn: $('equipment-cancel-btn') };
  let equipments = []; let zones = [];
  function setFeedback(message = '', type = '') { els.feedback.textContent = message; els.feedback.className = message ? `page-feedback ${type}`.trim() : 'page-feedback hidden'; }
  function filters() { return { search: els.search.value, status: els.filterStatus.value, type: els.filterType.value, zone_id: els.zoneFilter.value, include_archived: els.includeArchived.checked ? 'true' : '' }; }
  function fillZoneSelects() { els.zoneFilter.innerHTML = '<option value="">Toutes zones</option>' + zones.map((z) => `<option value="${z.id}">${z.code} - ${z.name}</option>`).join(''); els.zoneId.innerHTML = zones.filter((z) => z.status === 'active').map((z) => `<option value="${z.id}">${z.code} - ${z.name}</option>`).join(''); }
  function resetForm() { els.form.reset(); els.id.value = ''; els.status.value = 'active'; els.criticality.value = 'medium'; els.formTitle.textContent = 'Nouvel équipement'; fillZoneSelects(); els.formCard.classList.remove('hidden'); }
  function fillForm(e) { els.id.value = e.id; els.zoneId.innerHTML = zones.filter((z) => z.status === 'active' || z.id === e.zone_id).map((z) => `<option value="${z.id}">${z.code} - ${z.name}</option>`).join(''); els.zoneId.value = e.zone_id; els.code.value = e.code || ''; els.name.value = e.name || ''; els.type.value = e.type || ''; els.manufacturer.value = e.manufacturer || ''; els.model.value = e.model || ''; els.serial.value = e.serial_number || ''; els.supplier.value = e.supplier_name || ''; els.purchaseDate.value = e.purchase_date || ''; els.warrantyDate.value = e.warranty_end_date || ''; els.status.value = e.status || 'active'; els.criticality.value = e.criticality || 'medium'; els.foodContact.checked = Boolean(e.is_food_contact); els.temperature.checked = Boolean(e.is_temperature_controlled); els.cleaning.checked = Boolean(e.requires_cleaning); els.maintenance.checked = Boolean(e.requires_maintenance); els.calibration.checked = Boolean(e.requires_calibration); els.description.value = e.description || ''; els.formTitle.textContent = `Modifier ${e.name}`; els.formCard.classList.remove('hidden'); }
  function payload() { return { zone_id: els.zoneId.value, code: els.code.value, name: els.name.value, type: els.type.value, manufacturer: els.manufacturer.value, model: els.model.value, serial_number: els.serial.value, supplier_name: els.supplier.value, purchase_date: els.purchaseDate.value, warranty_end_date: els.warrantyDate.value, status: els.status.value, criticality: els.criticality.value, is_food_contact: els.foodContact.checked, is_temperature_controlled: els.temperature.checked, requires_cleaning: els.cleaning.checked, requires_maintenance: els.maintenance.checked, requires_calibration: els.calibration.checked, description: els.description.value }; }
  function documentHref(e) { return `./documents.html?owner_type=equipment&owner_id=${encodeURIComponent(e.id)}&label=${encodeURIComponent(e.name || e.code || 'Équipement')}`; }
  function render() { if (!equipments.length) { els.list.innerHTML = '<div class="quality-empty-state">Aucun équipement qualité trouvé.</div>'; return; } els.list.innerHTML = equipments.map((e) => `<article class="quality-card"><span class="quality-badge">${e.status}</span><h3>${e.name}</h3><p><strong>${e.code}</strong> · ${e.type}</p><p class="quality-muted">Zone : ${e.zone_code || '-'} - ${e.zone_name || '-'}</p><p class="quality-muted">Criticité : ${e.criticality} · Contact alimentaire : ${e.is_food_contact ? 'oui' : 'non'}</p><div class="quality-actions"><button class="btn btn-secondary" data-action="documents" data-id="${e.id}">Dossier</button><button class="btn btn-secondary" data-action="edit" data-id="${e.id}">Modifier</button><button class="btn btn-secondary" data-action="inactive" data-id="${e.id}">Désactiver</button><button class="btn btn-secondary" data-action="archive" data-id="${e.id}">Archiver</button><button class="btn btn-secondary" data-action="delete" data-id="${e.id}">Supprimer</button></div></article>`).join(''); if (!canManage) els.list.querySelectorAll('button:not([data-action="documents"])').forEach((button) => { button.disabled = true; }); }
  async function load() { setFeedback('Chargement des équipements...'); try { equipments = await api.listEquipments(filters()); setFeedback(''); render(); } catch (error) { setFeedback(error.message, 'error'); } }
  async function init() { zones = await api.listZones({ include_archived: 'true' }); fillZoneSelects(); els.addBtn.disabled = !canManage; await load(); }
  els.addBtn.addEventListener('click', resetForm); els.cancelBtn.addEventListener('click', () => els.formCard.classList.add('hidden')); [els.search, els.filterStatus, els.filterType, els.zoneFilter, els.includeArchived].forEach((el) => { el.addEventListener('input', load); el.addEventListener('change', load); });
  els.form.addEventListener('submit', async (event) => { event.preventDefault(); if (!canManage) return; try { const result = await api.saveEquipment(payload(), els.id.value || null); if (result.warning) setFeedback(result.warning, 'quality-warning'); els.formCard.classList.add('hidden'); await load(); } catch (error) { setFeedback(error.message, 'error'); } });
  els.list.addEventListener('click', async (event) => { const button = event.target.closest('button[data-action]'); if (!button) return; const equipment = equipments.find((item) => item.id === button.dataset.id); if (!equipment) return; if (button.dataset.action === 'documents') { window.location.href = documentHref(equipment); return; } if (!canManage) return; if (button.dataset.action === 'edit') return fillForm(equipment); if (button.dataset.action === 'delete' && !window.confirm('Supprimer cet équipement ?')) return; try { if (button.dataset.action === 'inactive') await api.setEquipmentStatus(equipment.id, 'inactive'); if (button.dataset.action === 'archive') await api.setEquipmentStatus(equipment.id, 'archived'); if (button.dataset.action === 'delete') await api.deleteEquipment(equipment.id); await load(); } catch (error) { setFeedback(error.message, 'error'); } });
  init().catch((error) => setFeedback(error.message, 'error'));
})();
