(function () {
  const sessionUser = JSON.parse(localStorage.getItem('gc_user') || localStorage.getItem('grv2_user') || 'null');
  const authToken = localStorage.getItem('gc_token') || localStorage.getItem('grv2_token');
  if (!sessionUser || !authToken) { window.location.href = '../../login.html'; return; }

  const tempApi = window.QualityTemperatureApi;
  const twinApi = window.QualityDigitalTwinApi;
  const canRecord = window.hasQualityPermission?.(sessionUser, 'quality.record.create');
  const canManage = window.hasQualityPermission?.(sessionUser, 'quality.equipment.manage');
  const $ = (id) => document.getElementById(id);
  const els = {
    feedback: $('temperature-feedback'), summary: $('temperature-summary'), addBtn: $('temperature-add-btn'), limitsBtn: $('temperature-limits-btn'),
    formCard: $('temperature-form-card'), form: $('temperature-form'), formTitle: $('temperature-form-title'), id: $('temperature-id'), type: $('temperature-type'), value: $('temperature-value'), unit: $('temperature-unit'), recordedAt: $('temperature-recorded-at'), source: $('temperature-source'), zoneId: $('temperature-zone-id'), equipmentId: $('temperature-equipment-id'), comment: $('temperature-comment'), cancelBtn: $('temperature-cancel-btn'),
    limitCard: $('temperature-limit-card'), limitForm: $('temperature-limit-form'), limitId: $('temperature-limit-id'), limitType: $('temperature-limit-type'), limitMin: $('temperature-limit-min'), limitMax: $('temperature-limit-max'), limitUnit: $('temperature-limit-unit'), limitZoneId: $('temperature-limit-zone-id'), limitEquipmentId: $('temperature-limit-equipment-id'), limitFrom: $('temperature-limit-from'), limitUntil: $('temperature-limit-until'), limitActive: $('temperature-limit-active'), limitCancelBtn: $('temperature-limit-cancel-btn'), limitList: $('temperature-limit-list'),
    search: $('temperature-search'), filterType: $('temperature-filter-type'), filterZone: $('temperature-filter-zone'), filterEquipment: $('temperature-filter-equipment'), filterAlert: $('temperature-filter-alert'), filterSource: $('temperature-filter-source'), startDate: $('temperature-start-date'), endDate: $('temperature-end-date'), exportCsv: $('temperature-export-csv'), chart: $('temperature-chart'), tableBody: $('temperature-table-body'),
  };
  let types = []; let zones = []; let equipments = []; let records = []; let limits = [];

  function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char])); }
  function setFeedback(message = '', type = '') { els.feedback.textContent = message; els.feedback.className = message ? `page-feedback ${type}`.trim() : 'page-feedback hidden'; }
  function formatDate(value) { return value ? new Date(value).toLocaleString('fr-FR') : '-'; }
  function toDatetimeLocal(value) { const date = value ? new Date(value) : new Date(); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
  function statusLabel(status) { if (status === 'compliant') return 'Conforme'; if (status === 'out_of_limits') return 'Hors limites'; return 'Surveillance'; }
  function statusClass(status) { if (status === 'compliant') return 'quality-temperature-ok'; if (status === 'out_of_limits') return 'quality-temperature-alert'; return 'quality-temperature-warning'; }
  function typeOptions(empty = false) { return `${empty ? '<option value="">Tous types</option>' : ''}${types.map((type) => `<option value="${escapeHtml(type.code)}">${escapeHtml(type.label)}</option>`).join('')}`; }
  function zoneOptions() { return `<option value="">Toutes zones</option>${zones.map((zone) => `<option value="${escapeHtml(zone.id)}">${escapeHtml(zone.code)} - ${escapeHtml(zone.name)}</option>`).join('')}`; }
  function equipmentOptions() { return `<option value="">Tous équipements</option>${equipments.map((equipment) => `<option value="${escapeHtml(equipment.id)}">${escapeHtml(equipment.code)} - ${escapeHtml(equipment.name)}</option>`).join('')}`; }
  function fillSelects() { els.type.innerHTML = typeOptions(); els.limitType.innerHTML = typeOptions(); els.filterType.innerHTML = typeOptions(true); els.zoneId.innerHTML = zoneOptions(); els.limitZoneId.innerHTML = zoneOptions(); els.filterZone.innerHTML = zoneOptions(); els.equipmentId.innerHTML = equipmentOptions(); els.limitEquipmentId.innerHTML = equipmentOptions(); els.filterEquipment.innerHTML = equipmentOptions(); }
  function filters() { return { search: els.search.value, type_code: els.filterType.value, zone_id: els.filterZone.value, equipment_id: els.filterEquipment.value, alert_status: els.filterAlert.value, source: els.filterSource.value, start_date: els.startDate.value, end_date: els.endDate.value }; }
  function recordPayload() { return { type_code: els.type.value, value: els.value.value, unit: els.unit.value || '°C', recorded_at: els.recordedAt.value ? new Date(els.recordedAt.value).toISOString() : new Date().toISOString(), source: els.source.value, zone_id: els.zoneId.value, equipment_id: els.equipmentId.value, comment: els.comment.value }; }
  function limitPayload() { return { type_code: els.limitType.value, min_value: els.limitMin.value, max_value: els.limitMax.value, unit: els.limitUnit.value || '°C', zone_id: els.limitZoneId.value, equipment_id: els.limitEquipmentId.value, valid_from: els.limitFrom.value, valid_until: els.limitUntil.value, is_active: els.limitActive.checked }; }
  function resetRecordForm() { els.form.reset(); els.id.value = ''; els.unit.value = '°C'; els.source.value = 'manual'; els.recordedAt.value = toDatetimeLocal(); els.formTitle.textContent = 'Nouveau relevé'; els.formCard.classList.remove('hidden'); }
  function fillRecordForm(record) { els.id.value = record.id; els.type.value = record.type_code; els.value.value = record.value; els.unit.value = record.unit || '°C'; els.recordedAt.value = toDatetimeLocal(record.recorded_at); els.source.value = record.source || 'manual'; els.zoneId.value = record.zone_id || ''; els.equipmentId.value = record.equipment_id || ''; els.comment.value = record.comment || ''; els.formTitle.textContent = 'Modifier le relevé'; els.formCard.classList.remove('hidden'); }
  function resetLimitForm() { els.limitForm.reset(); els.limitId.value = ''; els.limitUnit.value = '°C'; els.limitFrom.value = new Date().toISOString().slice(0, 10); els.limitActive.checked = true; }
  function fillLimitForm(limit) { els.limitId.value = limit.id; els.limitType.value = limit.type_code; els.limitMin.value = limit.min_value ?? ''; els.limitMax.value = limit.max_value ?? ''; els.limitUnit.value = limit.unit || '°C'; els.limitZoneId.value = limit.zone_id || ''; els.limitEquipmentId.value = limit.equipment_id || ''; els.limitFrom.value = limit.valid_from || ''; els.limitUntil.value = limit.valid_until || ''; els.limitActive.checked = Boolean(limit.is_active); }

  function renderSummary(summary) {
    const latest = Array.isArray(summary.latest) ? summary.latest.slice(0, 6) : [];
    const cards = latest.map((record) => `<article class="quality-card ${statusClass(record.alert_status)}"><span class="quality-badge">${statusLabel(record.alert_status)}</span><h3>${escapeHtml(record.equipment_name || record.zone_name || record.type_label)}</h3><p><strong>${escapeHtml(record.value)}${escapeHtml(record.unit || '°C')}</strong></p><p class="quality-muted">Dernier relevé : ${formatDate(record.recorded_at)}</p></article>`).join('');
    els.summary.innerHTML = `<article class="quality-card quality-temperature-alert"><span class="quality-badge">Alertes</span><h3>${summary.alert_count || 0}</h3><p class="quality-muted">Relevés hors limites</p></article><article class="quality-card quality-temperature-warning"><span class="quality-badge">Suivi</span><h3>${summary.equipment_without_records || 0}</h3><p class="quality-muted">Équipements température sans relevé</p></article>${cards || '<article class="quality-empty-state">Aucun relevé de température enregistré.</article>'}`;
  }
  function renderChart() { const recent = records.slice().reverse().slice(-20); if (!recent.length) { els.chart.innerHTML = '<div class="quality-empty-state">Aucune donnée pour le graphique.</div>'; return; } const values = recent.map((record) => Number(record.value)); const min = Math.min(...values); const max = Math.max(...values); const range = Math.max(max - min, 1); els.chart.innerHTML = recent.map((record) => `<div class="quality-temperature-bar ${statusClass(record.alert_status)}" style="height:${20 + ((Number(record.value) - min) / range) * 120}px" title="${escapeHtml(record.type_label)} · ${escapeHtml(record.value)}${escapeHtml(record.unit)} · ${formatDate(record.recorded_at)}"></div>`).join(''); }
  function renderRecords() { if (!records.length) { els.tableBody.innerHTML = '<tr><td colspan="8">Aucun relevé trouvé.</td></tr>'; renderChart(); return; } els.tableBody.innerHTML = records.map((record) => `<tr class="${statusClass(record.alert_status)}"><td>${formatDate(record.recorded_at)}</td><td>${escapeHtml(record.type_label)}</td><td>${escapeHtml(record.zone_name || '-')}</td><td>${escapeHtml(record.equipment_name || '-')}</td><td><strong>${escapeHtml(record.value)}${escapeHtml(record.unit || '°C')}</strong></td><td>${statusLabel(record.alert_status)}${record.alert_reason ? `<br><small>${escapeHtml(record.alert_reason)}</small>` : ''}</td><td>${escapeHtml(record.source)}</td><td><button class="btn btn-secondary" data-action="edit" data-id="${record.id}">Modifier</button> <button class="btn btn-secondary" data-action="delete" data-id="${record.id}">Archiver</button></td></tr>`).join(''); if (!canManage) els.tableBody.querySelectorAll('button').forEach((button) => { button.disabled = true; }); renderChart(); }
  function renderLimits() { if (!limits.length) { els.limitList.innerHTML = '<div class="quality-empty-state">Aucune limite configurée.</div>'; return; } els.limitList.innerHTML = limits.map((limit) => `<article class="quality-card"><span class="quality-badge">${limit.is_active ? 'Active' : 'Inactive'}</span><h3>${escapeHtml(limit.type_label || limit.type_code)}</h3><p>${limit.min_value ?? '-'}${escapeHtml(limit.unit)} à ${limit.max_value ?? '-'}${escapeHtml(limit.unit)}</p><p class="quality-muted">Zone : ${escapeHtml(limit.zone_name || '-')} · Équipement : ${escapeHtml(limit.equipment_name || '-')}</p><div class="quality-actions"><button class="btn btn-secondary" data-limit-action="edit" data-id="${limit.id}">Modifier</button><button class="btn btn-secondary" data-limit-action="delete" data-id="${limit.id}">Désactiver</button></div></article>`).join(''); if (!canManage) els.limitList.querySelectorAll('button').forEach((button) => { button.disabled = true; }); }
  async function loadAll() { setFeedback('Chargement des températures...'); try { const [summary, loadedRecords, loadedLimits] = await Promise.all([tempApi.getSummary(), tempApi.listRecords(filters()), tempApi.listLimits({ active_only: 'false' })]); records = loadedRecords; limits = loadedLimits; renderSummary(summary); renderRecords(); renderLimits(); setFeedback(''); } catch (error) { setFeedback(error.message, 'error'); } }
  function exportCsv() { const header = ['date', 'type', 'zone', 'equipement', 'valeur', 'unite', 'statut', 'origine', 'commentaire']; const lines = records.map((record) => [record.recorded_at, record.type_label, record.zone_name || '', record.equipment_name || '', record.value, record.unit, record.alert_status, record.source, record.comment || ''].map((value) => `"${String(value ?? '').replace(/"/g, '""')}"`).join(';')); const blob = new Blob([[header.join(';'), ...lines].join('\n')], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `temperatures-qms-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); }
  async function init() { types = await tempApi.listTypes(); zones = await twinApi.listZones({ include_archived: 'false' }); equipments = await twinApi.listEquipments({ include_archived: 'false' }); fillSelects(); resetLimitForm(); els.addBtn.disabled = !canRecord; els.limitsBtn.disabled = !canManage; await loadAll(); }

  els.addBtn.addEventListener('click', resetRecordForm); els.cancelBtn.addEventListener('click', () => els.formCard.classList.add('hidden')); els.limitsBtn.addEventListener('click', () => els.limitCard.classList.toggle('hidden')); els.limitCancelBtn.addEventListener('click', () => els.limitCard.classList.add('hidden')); els.exportCsv.addEventListener('click', exportCsv);
  [els.search, els.filterType, els.filterZone, els.filterEquipment, els.filterAlert, els.filterSource, els.startDate, els.endDate].forEach((el) => { el.addEventListener('input', loadAll); el.addEventListener('change', loadAll); });
  els.form.addEventListener('submit', async (event) => { event.preventDefault(); if (!canRecord && !els.id.value) return; if (!canManage && els.id.value) return; try { await tempApi.saveRecord(recordPayload(), els.id.value || null); els.formCard.classList.add('hidden'); await loadAll(); } catch (error) { setFeedback(error.message, 'error'); } });
  els.limitForm.addEventListener('submit', async (event) => { event.preventDefault(); if (!canManage) return; try { await tempApi.saveLimit(limitPayload(), els.limitId.value || null); resetLimitForm(); await loadAll(); } catch (error) { setFeedback(error.message, 'error'); } });
  els.tableBody.addEventListener('click', async (event) => { const button = event.target.closest('button[data-action]'); if (!button || !canManage) return; const record = records.find((item) => item.id === button.dataset.id); if (!record) return; if (button.dataset.action === 'edit') return fillRecordForm(record); if (button.dataset.action === 'delete' && !window.confirm('Archiver ce relevé ?')) return; try { await tempApi.deleteRecord(record.id); await loadAll(); } catch (error) { setFeedback(error.message, 'error'); } });
  els.limitList.addEventListener('click', async (event) => { const button = event.target.closest('button[data-limit-action]'); if (!button || !canManage) return; const limit = limits.find((item) => item.id === button.dataset.id); if (!limit) return; if (button.dataset.limitAction === 'edit') return fillLimitForm(limit); if (button.dataset.limitAction === 'delete' && !window.confirm('Désactiver cette limite ?')) return; try { await tempApi.deleteLimit(limit.id); await loadAll(); } catch (error) { setFeedback(error.message, 'error'); } });
  init().catch((error) => setFeedback(error.message, 'error'));
})();
