const token = localStorage.getItem("gc_token") || localStorage.getItem("grv2_token");
const sessionUser = JSON.parse(localStorage.getItem("gc_user") || localStorage.getItem("grv2_user") || "null");
const activeDepartment = JSON.parse(localStorage.getItem("gc_active_department") || localStorage.getItem("grv2_active_department") || "null");
if (!token || !sessionUser) window.location.href = "./login.html";
const API_BASE = window.APP_CONFIG.API_BASE_URL;
const saleId = new URLSearchParams(window.location.search).get("id");
if (!saleId) window.location.href = "./sales.html";
const $ = (id) => document.getElementById(id);
const els = { user: $("user-name"), logout: $("logout-btn"), back: $("back-sales-btn"), dep: $("topbar-department-select"), depName: $("current-department-name"), save: $("save-sale-btn"), validate: $("validate-sale-btn"), cancel: $("cancel-validation-btn"), add: $("add-line-btn"), hf: $("sale-header-feedback"), lf: $("sale-lines-feedback"), client: $("sale-client-id"), tariff: $("sale-tariff-level"), vat: $("sale-vat-context"), date: $("sale-document-date"), type: $("sale-document-type"), status: $("sale-status"), ref: $("sale-reference-number"), notes: $("sale-notes"), body: $("sale-lines-table-body"), stockModal: $("stock-article-modal"), closeStock: $("close-stock-article-modal-btn"), stockSearch: $("stock-article-search-input"), stockBody: $("stock-article-modal-table-body"), lotModal: $("lot-modal"), closeLot: $("close-lot-modal-btn"), lotBody: $("lot-modal-table-body") };
let sale = null, lines = [], clients = [], stockItems = [], lotItems = [], editingLineId = null;
function n(v, f = 0) { const x = Number(String(v ?? "").replace(',', '.')); return Number.isFinite(x) ? x : f; }
function clean(v) { return String(v ?? "").trim(); }
function money(v) { return n(v).toLocaleString("fr-FR", { minimumFractionDigits: 2, maximumFractionDigits: 2 }); }
function qty(v) { return n(v).toLocaleString("fr-FR", { minimumFractionDigits: 3, maximumFractionDigits: 3 }); }
function dinput(v) { if (!v) return ""; try { return new Date(v).toISOString().slice(0, 10); } catch { return ""; } }
function sdate(v) { if (!v) return "-"; try { return new Date(v).toLocaleDateString("fr-FR"); } catch { return v; } }
function fb(el, msg, err = false) { if (!el) return; el.textContent = msg; el.classList.remove("hidden"); el.classList.toggle("error", err); el.classList.toggle("success", !err); }
function clear(el) { if (!el) return; el.textContent = ""; el.classList.add("hidden"); el.classList.remove("error", "success"); }
async function api(path, options = {}) { const r = await fetch(`${API_BASE}${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...(options.headers || {}) } }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || "Erreur API"); return data; }
function deps() { return Array.isArray(sessionUser.departments) ? sessionUser.departments : []; }
function currentDep() { return activeDepartment && deps().some((d) => d.id === activeDepartment.id) ? activeDepartment : deps()[0] || null; }
function saveDep(dep) { localStorage.setItem("gc_active_department", JSON.stringify(dep)); localStorage.setItem("grv2_active_department", JSON.stringify(dep)); }
function selectedClient() { return clients.find((c) => c.id === els.client.value) || null; }
function tariffLevel() { return n(selectedClient()?.tariff_level || sale?.client_tariff_level || 1, 1); }
function vatRate() { const c = selectedClient(); if (c?.is_vat_exempt || sale?.client_is_vat_exempt) return 0; return n(c?.vat_rate ?? sale?.client_vat_rate ?? 5.5, 5.5); }
function priceFor(a) { return n(a?.[`sale_price_level_${tariffLevel()}_ht`] ?? a?.sale_price_ex_vat ?? 0, 0); }
function trace(line) { return line.selected_lot_traceability || line.suggested_lot_traceability || line.traceability_snapshot || {}; }
function traceText(t) { const parts = [t?.latin_name, t?.fao_zone, t?.sous_zone, t?.fishing_gear, t?.production_method, t?.allergens].filter(Boolean); return parts.length ? parts.join(" | ") : "-"; }
function renderTopbar() { if (els.user) els.user.textContent = sessionUser.email || "Utilisateur"; const list = deps(), dep = currentDep(); els.dep.innerHTML = ""; if (!list.length) { els.dep.innerHTML = `<option>Aucun service</option>`; els.dep.disabled = true; els.depName.textContent = "Aucun service"; return; } list.forEach((d) => { const o = document.createElement("option"); o.value = d.id; o.textContent = `${d.name} (${d.code})`; els.dep.appendChild(o); }); if (dep) { els.dep.value = dep.id; els.depName.textContent = dep.name || "-"; saveDep(dep); } els.dep.disabled = list.length === 1; els.dep.addEventListener("change", () => { const next = list.find((d) => d.id === els.dep.value); if (next) { saveDep(next); window.location.reload(); } }); }
async function loadClients() { clients = await api("/api/clients?status=active"); els.client.innerHTML = `<option value="">Sélectionner un client</option>` + clients.map((c) => `<option value="${c.id}">${c.name || c.legal_name || c.code || "Client"}</option>`).join(""); }
async function loadSale() { clear(els.hf); clear(els.lf); const data = await api(`/api/sales/${saleId}`); sale = data.sale; lines = Array.isArray(data.lines) ? data.lines : []; renderHeader(); renderLines(); }
function renderClientContext() { const c = selectedClient(); const level = c?.tariff_level || sale?.client_tariff_level || 1; const exempt = c?.is_vat_exempt || sale?.client_is_vat_exempt; const vat = exempt ? 0 : n(c?.vat_rate ?? sale?.client_vat_rate ?? 5.5, 5.5); els.tariff.value = `Tarif ${level}`; els.vat.value = exempt ? "Exonéré" : `${vat.toFixed(2)} %`; }
function renderHeader() { els.client.value = sale.client_id || ""; els.date.value = dinput(sale.document_date); els.type.value = sale.document_type || "ORDER"; els.status.value = sale.status || "draft"; els.ref.value = sale.reference_number || ""; els.notes.value = sale.notes || ""; renderClientContext(); const locked = sale.status === "validated"; [els.client, els.date, els.type, els.status, els.ref, els.notes].forEach((el) => { if (el) el.disabled = locked; }); els.save.disabled = locked; els.add.disabled = locked; els.validate.disabled = locked; els.cancel.classList.toggle("hidden", !locked); els.cancel.disabled = !locked; }
function renderLines() { if (!lines.length) { els.body.innerHTML = `<tr><td colspan="13">Aucune ligne</td></tr>`; return; } const locked = sale.status === "validated"; els.body.innerHTML = lines.map((line) => { const t = trace(line); const lot = line.selected_lot_code || line.suggested_lot_code || "FIFO à proposer"; return `<tr data-line-id="${line.id}" data-article-id="${line.article_id || ""}" data-selected-lot-id="${line.selected_lot_id || ""}"><td><input class="line-input line-plu" value="${line.article_plu_resolved || line.article_plu || ""}" ${locked ? "disabled" : ""}/></td><td><input class="line-input line-article-label" value="${line.article_name || line.article_label || ""}" readonly /></td><td><button type="button" class="btn btn-secondary btn-sm line-lot-btn" data-action="choose-lot" data-id="${line.id}" ${locked || !line.article_id ? "disabled" : ""}>${lot}</button><div class="line-muted">DLC ${sdate(line.selected_lot_dlc || line.suggested_lot_dlc || t.dlc)}</div></td><td><input class="line-input line-package-count" type="number" step="0.001" value="${line.package_count ?? ""}" ${locked ? "disabled" : ""}/></td><td><input class="line-input line-weight-per-package" type="number" step="0.001" value="${line.weight_per_package ?? ""}" ${locked ? "disabled" : ""}/></td><td><input class="line-input line-total-weight" type="number" step="0.001" value="${line.total_weight || line.sold_quantity || ""}" ${locked ? "disabled" : ""}/></td><td><input class="line-input line-unit-price-ht" type="number" step="0.0001" value="${line.unit_sale_price_ht ?? ""}" ${locked ? "disabled" : ""}/></td><td><input class="line-input line-total-ht" value="${money(line.line_amount_ht)}" readonly /></td><td><input class="line-input line-vat-rate" type="number" step="0.01" value="${line.vat_rate ?? vatRate()}" ${locked ? "disabled" : ""}/></td><td><input class="line-input line-total-ttc" value="${money(line.line_amount_ttc)}" readonly /></td><td><div class="trace-cell" title="${traceText(t)}">${traceText(t)}</div></td><td>${line.line_status || "-"}</td><td><div class="page-actions-right">${locked ? "" : `<button class="btn btn-secondary btn-sm" data-action="save-line" data-id="${line.id}">Enregistrer</button><button class="btn btn-danger btn-sm" data-action="delete-line" data-id="${line.id}">Supprimer</button>`}</div></td></tr>`; }).join(""); }
function computeRow(row) { const p = n(row.querySelector(".line-package-count")?.value); const w = n(row.querySelector(".line-weight-per-package")?.value); const totalInput = row.querySelector(".line-total-weight"); const calcWeight = Number((p * w).toFixed(3)); if (calcWeight > 0 && document.activeElement !== totalInput) totalInput.value = calcWeight.toFixed(3); const weight = n(totalInput?.value, calcWeight); const ht = n(row.querySelector(".line-unit-price-ht")?.value); const vat = n(row.querySelector(".line-vat-rate")?.value, vatRate()); const totalHt = Number((weight * ht).toFixed(2)); const vatAmount = Number((totalHt * vat / 100).toFixed(2)); row.querySelector(".line-total-ht").value = money(totalHt); row.querySelector(".line-total-ttc").value = money(totalHt + vatAmount); }
async function stockSearch(q = "") { const p = new URLSearchParams({ available_only: "true", limit: "50" }); if (q) p.set("search", q); stockItems = await api(`/api/stock?${p}`); renderStock(); }
function renderStock() { if (!stockItems.length) { els.stockBody.innerHTML = `<tr><td colspan="8">Aucun article en stock.</td></tr>`; return; } els.stockBody.innerHTML = stockItems.map((a) => `<tr data-article-id="${a.article_id}"><td>${a.plu || "-"}</td><td>${a.designation || "-"}</td><td>${qty(a.stock_quantity)}</td><td>${money(a.pma)}</td><td>${money(a.sale_price_level_1_ht)}</td><td>${money(a.sale_price_level_2_ht)}</td><td>${money(a.sale_price_level_3_ht)}</td><td>${sdate(a.next_lot_dlc || a.next_dlc)}</td></tr>`).join(""); }
function openStock(lineId) { editingLineId = lineId; els.stockModal.classList.remove("hidden"); els.stockSearch.value = ""; els.stockSearch.focus(); stockSearch().catch((e) => fb(els.lf, e.message, true)); }
function applyArticle(a) { const row = els.body.querySelector(`tr[data-line-id="${editingLineId}"]`); if (!row) return; row.dataset.articleId = a.article_id; row.dataset.selectedLotId = ""; row.querySelector(".line-plu").value = a.plu || ""; row.querySelector(".line-article-label").value = a.designation || ""; row.querySelector(".line-unit-price-ht").value = priceFor(a).toFixed(4); row.querySelector(".line-vat-rate").value = vatRate().toFixed(2); row.querySelector(".line-lot-btn").textContent = a.next_lot_code || "FIFO proposé"; row.querySelector(".line-lot-btn").disabled = false; computeRow(row); els.stockModal.classList.add("hidden"); }
async function resolvePlu(row) { const plu = clean(row.querySelector(".line-plu")?.value); if (!plu) return; const p = new URLSearchParams({ search: plu, available_only: "true", limit: "20" }); const results = await api(`/api/stock?${p}`); const exact = Array.isArray(results) ? results.find((a) => String(a.plu || "").trim() === plu) : null; if (!exact) return; editingLineId = row.dataset.lineId; applyArticle(exact); }
async function openLots(lineId) { const row = els.body.querySelector(`tr[data-line-id="${lineId}"]`); const articleId = row?.dataset.articleId; if (!articleId) return; editingLineId = lineId; lotItems = await api(`/api/stock/articles/${articleId}/lots?available_only=true`); els.lotBody.innerHTML = lotItems.length ? lotItems.map((l) => `<tr data-lot-id="${l.id}"><td>${l.lot_code || "-"}</td><td>${l.supplier_lot_number || "-"}</td><td>${qty(l.qty_remaining)}</td><td>${sdate(l.dlc)}</td><td>${l.latin_name || "-"}</td><td>${l.fao_zone || "-"}</td><td>${l.sous_zone || "-"}</td><td>${l.fishing_gear || "-"}</td><td>${l.production_method || "-"}</td><td>${l.allergens || "-"}</td></tr>`).join("") : `<tr><td colspan="10">Aucun lot disponible.</td></tr>`; els.lotModal.classList.remove("hidden"); }
function applyLot(lot) { const row = els.body.querySelector(`tr[data-line-id="${editingLineId}"]`); if (!row) return; row.dataset.selectedLotId = lot.id; row.querySelector(".line-lot-btn").textContent = lot.lot_code || "Lot choisi"; els.lotModal.classList.add("hidden"); }
async function saveHeader(reload = true) { clear(els.hf); await api(`/api/sales/${saleId}`, { method: "PATCH", body: JSON.stringify({ client_id: els.client.value || null, document_date: els.date.value || null, document_type: els.type.value || "ORDER", status: els.status.value || "draft", origin: "manual", reference_number: clean(els.ref.value) || null, notes: clean(els.notes.value) || null }) }); if (reload) { fb(els.hf, "En-tête enregistré"); await loadSale(); } }
async function ensureHeader() { if ((sale?.client_id || "") === (els.client.value || "")) return; await saveHeader(false); const data = await api(`/api/sales/${saleId}`); sale = data.sale; lines = Array.isArray(data.lines) ? data.lines : []; }
async function addLine() { clear(els.lf); if (!els.client.value) { fb(els.lf, "Sélectionne un client avant d'ajouter une ligne", true); return; } await ensureHeader(); await api(`/api/sales/${saleId}/lines`, { method: "POST", body: JSON.stringify({}) }); await loadSale(); els.body.querySelector("tr[data-line-id]:last-child .line-plu")?.focus(); }
async function saveLine(lineId) { clear(els.lf); await ensureHeader(); const row = els.body.querySelector(`tr[data-line-id="${lineId}"]`); if (!row) return; if (!row.dataset.articleId) await resolvePlu(row); if (!row.dataset.articleId) { fb(els.lf, "Sélectionne un article en stock", true); return; } const payload = { article_id: row.dataset.articleId, article_plu: clean(row.querySelector(".line-plu").value), article_label: clean(row.querySelector(".line-article-label").value), selected_lot_id: row.dataset.selectedLotId || null, package_count: n(row.querySelector(".line-package-count").value), weight_per_package: n(row.querySelector(".line-weight-per-package").value), total_weight: n(row.querySelector(".line-total-weight").value), sale_unit: "kg", unit_sale_price_ht: n(row.querySelector(".line-unit-price-ht").value), vat_rate: n(row.querySelector(".line-vat-rate").value, vatRate()) }; await api(`/api/sales/lines/${lineId}`, { method: "PATCH", body: JSON.stringify(payload) }); fb(els.lf, "Ligne enregistrée"); await loadSale(); }
async function deleteLine(lineId) { clear(els.lf); if (!confirm("Supprimer cette ligne ?")) return; await api(`/api/sales/lines/${lineId}`, { method: "DELETE" }); fb(els.lf, "Ligne supprimée"); await loadSale(); }
async function validateSale() { clear(els.lf); if (!confirm("Confirmer la validation et la sortie réelle du stock ?")) return; await api(`/api/sales/${saleId}/validate`, { method: "POST", body: JSON.stringify({}) }); fb(els.lf, "Commande validée et stock consommé"); await loadSale(); }
async function cancelValidation() { clear(els.lf); if (!confirm("Annuler la validation et remettre le stock ?")) return; await api(`/api/sales/${saleId}/cancel-validation`, { method: "POST", body: JSON.stringify({}) }); fb(els.lf, "Validation annulée"); await loadSale(); }
els.logout?.addEventListener("click", () => { localStorage.removeItem("gc_token"); localStorage.removeItem("gc_user"); localStorage.removeItem("gc_active_department"); localStorage.removeItem("grv2_token"); localStorage.removeItem("grv2_user"); localStorage.removeItem("grv2_active_department"); window.location.href = "./login.html"; });
els.back?.addEventListener("click", () => { window.location.href = "./sales.html"; });
els.save?.addEventListener("click", () => saveHeader(true));
els.add?.addEventListener("click", addLine);
els.validate?.addEventListener("click", validateSale);
els.cancel?.addEventListener("click", cancelValidation);
els.client?.addEventListener("change", renderClientContext);
els.closeStock?.addEventListener("click", () => els.stockModal.classList.add("hidden"));
els.closeLot?.addEventListener("click", () => els.lotModal.classList.add("hidden"));
els.stockSearch?.addEventListener("input", () => stockSearch(clean(els.stockSearch.value)).catch((e) => fb(els.lf, e.message, true)));
els.stockBody?.addEventListener("dblclick", (e) => { const row = e.target.closest("tr[data-article-id]"); const item = stockItems.find((a) => a.article_id === row?.dataset.articleId); if (item) applyArticle(item); });
els.lotBody?.addEventListener("dblclick", (e) => { const row = e.target.closest("tr[data-lot-id]"); const lot = lotItems.find((l) => l.id === row?.dataset.lotId); if (lot) applyLot(lot); });
els.body?.addEventListener("click", async (e) => { const b = e.target.closest("[data-action]"); if (!b) return; if (b.dataset.action === "save-line") await saveLine(b.dataset.id); if (b.dataset.action === "delete-line") await deleteLine(b.dataset.id); if (b.dataset.action === "choose-lot") await openLots(b.dataset.id); });
els.body?.addEventListener("keydown", async (e) => { const row = e.target.closest("tr[data-line-id]"); if (!row) return; if (e.key === "F9" && e.target.classList.contains("line-plu")) { e.preventDefault(); openStock(row.dataset.lineId); return; } if (e.key !== "Enter" || !e.target.classList.contains("line-input")) return; e.preventDefault(); await saveLine(row.dataset.lineId); await addLine(); });
els.body?.addEventListener("blur", async (e) => { if (!e.target.classList.contains("line-plu")) return; const row = e.target.closest("tr[data-line-id]"); if (row) await resolvePlu(row).catch((err) => fb(els.lf, err.message, true)); }, true);
els.body?.addEventListener("input", (e) => { const row = e.target.closest("tr[data-line-id]"); if (!row) return; if (["line-package-count", "line-weight-per-package", "line-total-weight", "line-unit-price-ht", "line-vat-rate"].some((c) => e.target.classList.contains(c))) computeRow(row); });
async function init() { try { renderTopbar(); await loadClients(); await loadSale(); } catch (e) { console.error("Erreur init détail vente :", e); fb(els.lf, e.message || "Erreur chargement vente", true); } }
init();
