-- ALTA Quality PMS architecture hardening.
-- Additive/idempotent migration: distinguish user tasks from tasks generated by native ALTA sources,
-- then align the digital twin data used by the cleaning-plan source of truth.

ALTER TABLE quality_tasks
  ADD COLUMN IF NOT EXISTS task_origin text NOT NULL DEFAULT 'MANUAL',
  ADD COLUMN IF NOT EXISTS source_entity_type text,
  ADD COLUMN IF NOT EXISTS source_entity_id uuid,
  ADD COLUMN IF NOT EXISTS source_locked boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS archived_at timestamptz,
  ADD COLUMN IF NOT EXISTS archived_by uuid REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE quality_temperature_limits
  ADD COLUMN IF NOT EXISTS responsible_user_id uuid REFERENCES users(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_quality_temperature_limits_responsible
  ON quality_temperature_limits (store_id, responsible_user_id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'quality_tasks_task_origin_check'
      AND conrelid = 'quality_tasks'::regclass
  ) THEN
    ALTER TABLE quality_tasks
      ADD CONSTRAINT quality_tasks_task_origin_check
      CHECK (task_origin IN ('SYSTEM', 'MANUAL'));
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_quality_tasks_origin_status
  ON quality_tasks (store_id, task_origin, configuration_status);

CREATE INDEX IF NOT EXISTS idx_quality_tasks_source_entity
  ON quality_tasks (store_id, source_entity_type, source_entity_id);

UPDATE quality_tasks qt
SET task_origin = 'SYSTEM',
    source_entity_type = 'cleaning_plan',
    source_entity_id = p.id,
    source_locked = true,
    created_source = COALESCE(NULLIF(qt.created_source, ''), 'cleaning_plan'),
    category = COALESCE(NULLIF(qt.category, ''), 'cleaning_plan'),
    updated_at = now()
FROM quality_cleaning_plans p
WHERE p.quality_task_id = qt.id
  AND p.store_id = qt.store_id
  AND (
    qt.task_origin IS DISTINCT FROM 'SYSTEM'
    OR qt.source_entity_type IS DISTINCT FROM 'cleaning_plan'
    OR qt.source_entity_id IS DISTINCT FROM p.id
    OR qt.source_locked IS DISTINCT FROM true
  );

UPDATE quality_tasks qt
SET task_origin = 'SYSTEM',
    source_entity_type = 'temperature_parameter',
    source_entity_id = l.id,
    source_locked = true,
    created_source = COALESCE(NULLIF(qt.created_source, ''), 'temperature_parameter'),
    category = COALESCE(NULLIF(qt.category, ''), 'temperature_parameter'),
    updated_at = now()
FROM quality_temperature_limits l
WHERE l.quality_task_id = qt.id
  AND l.store_id = qt.store_id
  AND (
    qt.task_origin IS DISTINCT FROM 'SYSTEM'
    OR qt.source_entity_type IS DISTINCT FROM 'temperature_parameter'
    OR qt.source_entity_id IS DISTINCT FROM l.id
    OR qt.source_locked IS DISTINCT FROM true
  );

DO $$
DECLARE
  moved_cf integer := 0;
  already_cf integer := 0;
  marked_contact integer := 0;
  already_contact integer := 0;
  plan_links integer := 0;
  already_plan_links integer := 0;
BEGIN
  SELECT count(*) INTO already_cf
  FROM quality_equipments e
  INNER JOIN quality_zones z ON z.id = e.zone_id AND z.store_id = e.store_id
  WHERE e.code IN ('PORTE-CF01', 'GF-CF01')
    AND z.code = 'RDC-CF01'
    AND e.deleted_at IS NULL;

  WITH target_zone AS (
    SELECT store_id, id AS zone_id
    FROM quality_zones
    WHERE code = 'RDC-CF01' AND deleted_at IS NULL
  ),
  changed AS (
    UPDATE quality_equipments e
    SET zone_id = tz.zone_id,
        updated_at = now()
    FROM target_zone tz
    WHERE e.store_id = tz.store_id
      AND e.code IN ('PORTE-CF01', 'GF-CF01')
      AND e.deleted_at IS NULL
      AND e.zone_id IS DISTINCT FROM tz.zone_id
    RETURNING e.id
  )
  SELECT count(*) INTO moved_cf FROM changed;

  SELECT count(*) INTO already_contact
  FROM quality_equipments
  WHERE code IN ('PLANCHE-LOT01', 'PELLE-GLACE01')
    AND is_food_contact = true
    AND deleted_at IS NULL;

  WITH changed AS (
    UPDATE quality_equipments
    SET is_food_contact = true,
        updated_at = now()
    WHERE code IN ('PLANCHE-LOT01', 'PELLE-GLACE01')
      AND deleted_at IS NULL
      AND is_food_contact IS DISTINCT FROM true
    RETURNING id
  )
  SELECT count(*) INTO marked_contact FROM changed;

  SELECT count(*) INTO already_plan_links
  FROM quality_cleaning_plans p
  INNER JOIN quality_cleaning_plan_equipments pe ON pe.plan_id = p.id AND pe.deleted_at IS NULL
  INNER JOIN quality_equipments e ON e.id = pe.equipment_id AND e.store_id = p.store_id
  WHERE lower(p.title) = lower('Chambre froide')
    AND e.code IN ('PORTE-CF01', 'GF-CF01');

  WITH targets AS (
    SELECT p.id AS plan_id, e.id AS equipment_id, p.created_by
    FROM quality_cleaning_plans p
    INNER JOIN quality_equipments e ON e.store_id = p.store_id
    WHERE lower(p.title) = lower('Chambre froide')
      AND p.configuration_status IS DISTINCT FROM 'archived'
      AND e.code IN ('PORTE-CF01', 'GF-CF01')
      AND e.deleted_at IS NULL
  ),
  inserted AS (
    INSERT INTO quality_cleaning_plan_equipments (plan_id, equipment_id, created_at, created_by)
    SELECT t.plan_id, t.equipment_id, now(), t.created_by
    FROM targets t
    WHERE NOT EXISTS (
      SELECT 1
      FROM quality_cleaning_plan_equipments pe
      WHERE pe.plan_id = t.plan_id
        AND pe.equipment_id = t.equipment_id
        AND pe.deleted_at IS NULL
    )
    ON CONFLICT (plan_id, equipment_id)
    DO UPDATE SET deleted_at = NULL, deleted_by = NULL
    RETURNING plan_id
  )
  SELECT count(*) INTO plan_links FROM inserted;

  RAISE NOTICE 'PMS digital twin fix: cold-room equipment moved=%, already_conforming=%', moved_cf, already_cf;
  RAISE NOTICE 'PMS digital twin fix: food-contact equipment marked=%, already_conforming=%', marked_contact, already_contact;
  RAISE NOTICE 'PMS cleaning plan Chambre froide: links_added=%, already_linked=%; THERM-CF01 intentionally untouched', plan_links, already_plan_links;
END
$$;
